# Generated by Django 2.0.1 on 2020-01-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rsvp_not_coming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSVP',
        ),
    ]
